#!/usr/bin/env python3
"""
site_builder.py — turns daily reflections into a small static website.

Called by daily_readings_email.py after a reflection is generated. Writes:

    docs/index.html            today's reflection (the homepage)
    docs/YYYY-MM-DD.html       a permanent page for each day
    docs/archive.html          list of every past day
    docs/style.css             shared styling
    docs/manifest.json         makes the site installable to a phone homescreen
    docs/reflections.json      machine-readable record of all entries

GitHub Pages serves the docs/ folder directly, so committing these files
publishes them. Nothing here talks to the network.
"""

import os
import re
import json
import html
import datetime

DOCS_DIR = "docs"
SITE_TITLE = "Daily Readings"
SITE_TAGLINE = "The day's Mass readings, with a reflection"

DISCLOSURE = (
    "Reflections are generated by AI from the day's readings and are offered "
    "as a starting point for prayer, not as authoritative commentary."
)


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------
def _md_to_html(text: str) -> str:
    """
    Convert the light markdown Claude produces (bold headers, paragraphs)
    into simple HTML. Deliberately minimal — no external dependency.
    """
    text = html.escape(text)

    # **bold** -> <strong>
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)

    # Split into paragraphs on blank lines.
    chunks = [c.strip() for c in re.split(r"\n\s*\n", text) if c.strip()]

    out = []
    for chunk in chunks:
        lines = [l.strip() for l in chunk.split("\n") if l.strip()]

        # A chunk that is entirely list items becomes a <ul>.
        if all(l.startswith(("- ", "* ")) for l in lines):
            items = "".join(f"<li>{l[2:].strip()}</li>" for l in lines)
            out.append(f"<ul>{items}</ul>")
            continue

        # A short chunk that is wholly bold reads as a heading.
        if len(lines) == 1 and lines[0].startswith("<strong>") \
                and lines[0].endswith("</strong>") and len(lines[0]) < 120:
            inner = lines[0][8:-9]
            out.append(f"<h2>{inner}</h2>")
            continue

        out.append("<p>" + "<br>".join(lines) + "</p>")

    return "\n".join(out)


def _split_carry(body_html: str):
    """
    Pull the 'To carry today' section out of the reflection so it can be
    styled separately. Returns (main_html, carry_html_or_None).
    """
    marker = re.search(
        r"<h2>\s*To carry today\s*</h2>", body_html, flags=re.IGNORECASE
    )
    if not marker:
        return body_html, None
    main = body_html[:marker.start()].strip()
    carry = body_html[marker.end():].strip()
    return main, carry


def _page_shell(title: str, body: str, description: str = "") -> str:
    """Wrap page content in the shared HTML shell."""
    desc = html.escape(description or SITE_TAGLINE)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<meta name="description" content="{desc}">
<meta name="theme-color" content="#faf9f7">
<meta property="og:title" content="{html.escape(title)}">
<meta property="og:description" content="{desc}">
<meta property="og:type" content="article">
<link rel="manifest" href="manifest.json">
<link rel="stylesheet" href="style.css">
<link rel="apple-touch-icon" href="icon.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="{html.escape(SITE_TITLE)}">
</head>
<body>
<div class="wrap">
  <header class="site-head">
    <a class="brand" href="index.html">{html.escape(SITE_TITLE)}</a>
    <a class="archive-link" href="archive.html">Archive</a>
  </header>
{body}
  <footer class="site-foot">
    <p class="disclosure">{html.escape(DISCLOSURE)}</p>
  </footer>
</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Page builders
# ---------------------------------------------------------------------------
def _reflection_page(entry: dict, prev_date: str = None,
                     next_date: str = None) -> str:
    """Build one day's reflection page."""
    date_obj = datetime.date.fromisoformat(entry["date"])
    pretty_date = date_obj.strftime("%A, %B %-d, %Y")

    body_html = _md_to_html(entry["reflection"])
    main_html, carry_html = _split_carry(body_html)

    heading = entry.get("liturgical_day") or pretty_date

    nav_parts = []
    if prev_date:
        nav_parts.append(
            f'<a class="nav-prev" href="{prev_date}.html">'
            f'&larr; {datetime.date.fromisoformat(prev_date).strftime("%b %-d")}</a>'
        )
    else:
        nav_parts.append("<span></span>")

    if next_date:
        nav_parts.append(
            f'<a class="nav-next" href="{next_date}.html">'
            f'{datetime.date.fromisoformat(next_date).strftime("%b %-d")} &rarr;</a>'
        )
    else:
        nav_parts.append('<span class="nav-today">Today</span>')

    carry_block = ""
    if carry_html:
        carry_block = f"""
    <section class="carry">
      <p class="carry-label">To carry today</p>
      {carry_html}
    </section>"""

    body = f"""
  <article class="entry">
    <p class="date">{html.escape(pretty_date)}</p>
    <h1>{html.escape(heading)}</h1>
    <div class="reflection">
{main_html}
    </div>{carry_block}
    <nav class="daynav">
      {nav_parts[0]}
      {nav_parts[1]}
    </nav>
  </article>
"""
    return _page_shell(f"{heading} — {SITE_TITLE}", body,
                       description=f"Readings and reflection for {pretty_date}")


def _archive_page(entries: list) -> str:
    """Build the archive index, grouped by month, newest first."""
    by_month = {}
    for e in entries:
        d = datetime.date.fromisoformat(e["date"])
        by_month.setdefault(d.strftime("%B %Y"), []).append(e)

    sections = []
    for month, items in by_month.items():
        rows = []
        for e in items:
            d = datetime.date.fromisoformat(e["date"])
            label = e.get("liturgical_day") or d.strftime("%A")
            rows.append(
                f'<li><a href="{e["date"]}.html">'
                f'<span class="a-date">{d.strftime("%-d %a")}</span>'
                f'<span class="a-title">{html.escape(label)}</span></a></li>'
            )
        sections.append(
            f'<section class="month"><h2>{html.escape(month)}</h2>'
            f'<ul class="archive-list">{"".join(rows)}</ul></section>'
        )

    inner = "".join(sections) if sections else \
        '<p class="empty">No reflections yet.</p>'

    body = f"""
  <div class="entry">
    <h1>Archive</h1>
    {inner}
  </div>
"""
    return _page_shell(f"Archive — {SITE_TITLE}", body)


STYLE_CSS = """:root {
  --bg: #faf9f7;
  --card: #ffffff;
  --ink: #23201c;
  --ink-soft: #5c574f;
  --ink-faint: #8b8579;
  --rule: #e5e1d8;
  --accent: #7a5c3e;
}
@media (prefers-color-scheme: dark) {
  :root {
    --bg: #16150f;
    --card: #1e1c17;
    --ink: #ebe7df;
    --ink-soft: #b3ada1;
    --ink-faint: #837d72;
    --rule: #322e27;
    --accent: #c9a67c;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--bg);
  color: var(--ink);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}
.wrap { max-width: 40rem; margin: 0 auto; padding: 1.25rem 1.15rem 3rem; }
.site-head {
  display: flex; justify-content: space-between; align-items: center;
  padding-bottom: .75rem; border-bottom: 1px solid var(--rule);
  margin-bottom: 1.75rem;
}
.brand {
  font-size: .95rem; font-weight: 600; letter-spacing: .01em;
  color: var(--ink); text-decoration: none;
}
.archive-link { font-size: .875rem; color: var(--ink-faint); text-decoration: none; }
.archive-link:hover { color: var(--accent); }
.entry {
  background: var(--card); border: 1px solid var(--rule);
  border-radius: 14px; padding: 2rem 1.6rem;
}
.date { font-size: .8rem; color: var(--ink-faint); margin: 0 0 .3rem; }
h1 {
  font-family: Georgia, "Iowan Old Style", serif;
  font-size: 1.55rem; font-weight: 600; line-height: 1.25;
  margin: 0 0 1.5rem;
}
.reflection {
  font-family: Georgia, "Iowan Old Style", serif;
  font-size: 1.06rem; line-height: 1.75;
}
.reflection h2 {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  font-size: .82rem; font-weight: 600; text-transform: uppercase;
  letter-spacing: .07em; color: var(--ink-faint);
  margin: 2rem 0 .6rem;
}
.reflection p { margin: 0 0 1.1rem; }
.reflection ul { margin: 0 0 1.1rem; padding-left: 1.2rem; }
.reflection li { margin-bottom: .4rem; }
.reflection strong { font-weight: 600; }
.carry {
  margin-top: 2rem; padding-top: 1.25rem; border-top: 1px solid var(--rule);
}
.carry-label {
  font-size: .78rem; font-weight: 600; text-transform: uppercase;
  letter-spacing: .07em; color: var(--ink-faint); margin: 0 0 .5rem;
}
.carry p {
  font-family: Georgia, "Iowan Old Style", serif;
  font-size: 1.04rem; line-height: 1.65; margin: 0; color: var(--ink);
}
.daynav {
  display: flex; justify-content: space-between; align-items: center;
  margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--rule);
  font-size: .875rem;
}
.daynav a { color: var(--accent); text-decoration: none; }
.nav-today { color: var(--ink-faint); }
.month h2 {
  font-size: .82rem; font-weight: 600; text-transform: uppercase;
  letter-spacing: .07em; color: var(--ink-faint);
  margin: 1.75rem 0 .6rem;
}
.archive-list { list-style: none; margin: 0; padding: 0; }
.archive-list li { border-bottom: 1px solid var(--rule); }
.archive-list a {
  display: flex; gap: .9rem; padding: .7rem 0;
  text-decoration: none; color: var(--ink);
}
.archive-list a:hover .a-title { color: var(--accent); }
.a-date {
  flex: 0 0 3.6rem; font-size: .82rem; color: var(--ink-faint);
  font-variant-numeric: tabular-nums;
}
.a-title { font-size: .94rem; }
.empty { color: var(--ink-faint); }
.site-foot { margin-top: 2rem; }
.disclosure {
  font-size: .74rem; line-height: 1.5; color: var(--ink-faint);
  margin: 0; text-align: center;
}
"""

MANIFEST = {
    "name": SITE_TITLE,
    "short_name": "Readings",
    "description": SITE_TAGLINE,
    "start_url": "index.html",
    "display": "standalone",
    "background_color": "#faf9f7",
    "theme_color": "#faf9f7",
    "icons": [
        {"src": "icon.png", "sizes": "512x512", "type": "image/png",
         "purpose": "any maskable"}
    ],
}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def build_site(date: datetime.date, reflection: str,
               liturgical_day: str = None) -> str:
    """
    Add today's reflection to the site and regenerate all pages.
    Returns the relative URL path of today's page (e.g. "2026-07-22.html").
    """
    os.makedirs(DOCS_DIR, exist_ok=True)

    record_path = os.path.join(DOCS_DIR, "reflections.json")
    entries = []
    if os.path.exists(record_path):
        try:
            with open(record_path, encoding="utf-8") as f:
                entries = json.load(f)
        except (json.JSONDecodeError, OSError):
            entries = []

    iso = date.isoformat()
    entries = [e for e in entries if e.get("date") != iso]   # replace if re-run
    entries.append({
        "date": iso,
        "liturgical_day": liturgical_day,
        "reflection": reflection,
    })
    entries.sort(key=lambda e: e["date"], reverse=True)

    with open(record_path, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2, ensure_ascii=False)

    # Rebuild every dated page so navigation links stay correct.
    for i, entry in enumerate(entries):
        newer = entries[i - 1]["date"] if i > 0 else None
        older = entries[i + 1]["date"] if i + 1 < len(entries) else None
        page = _reflection_page(entry, prev_date=older, next_date=newer)
        with open(os.path.join(DOCS_DIR, f'{entry["date"]}.html'), "w",
                  encoding="utf-8") as f:
            f.write(page)

    # Homepage is a copy of the newest entry.
    newest = entries[0]
    home = _reflection_page(
        newest,
        prev_date=entries[1]["date"] if len(entries) > 1 else None,
        next_date=None,
    )
    with open(os.path.join(DOCS_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(home)

    with open(os.path.join(DOCS_DIR, "archive.html"), "w", encoding="utf-8") as f:
        f.write(_archive_page(entries))

    with open(os.path.join(DOCS_DIR, "style.css"), "w", encoding="utf-8") as f:
        f.write(STYLE_CSS)

    with open(os.path.join(DOCS_DIR, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(MANIFEST, f, indent=2)

    # Stops GitHub Pages from running the files through Jekyll.
    open(os.path.join(DOCS_DIR, ".nojekyll"), "w").close()

    return f"{iso}.html"
