#!/usr/bin/env python3
"""
site_builder.py — turns daily reflections into a small static website.

Called by daily_readings.py after a reflection is generated. Writes:

    docs/index.html            today's reflection (the homepage)
    docs/YYYY-MM-DD.html       a permanent page for each day
    docs/archive.html          list of every past day
    docs/style.css             shared styling
    docs/manifest.json         makes the site installable to a phone homescreen
    docs/reflections.json      machine-readable record of all entries

GitHub Pages serves the docs/ folder directly, so committing these files
publishes them. Nothing here talks to the network.
"""

import os
import re
import json
import html
import datetime

DOCS_DIR = "docs"
SITE_TITLE = "Daily Readings"
SITE_TAGLINE = "The day's Mass readings, with a reflection"

DISCLOSURE = (
    "Reflections are generated by AI from the day's readings and are offered "
    "as a starting point for prayer, not as authoritative commentary."
)

# Liturgical colors, used as a thin accent band at the top of each page.
SEASON_COLORS = {
    "green": "#5b7f4a",    # Ordinary Time
    "purple": "#6b5580",   # Advent, Lent
    "red": "#963c36",      # martyrs, Pentecost, Passion
    "white": "#c2a878",    # feasts of the Lord, Mary, non-martyr saints
    "rose": "#c08b96",     # Gaudete, Laetare
}
DEFAULT_COLOR = "green"


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------
def _md_to_html(text: str) -> str:
    """Convert the light markdown Claude produces into simple HTML."""
    text = html.escape(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*(?!\s)(.+?)(?<!\s)\*(?!\*)", r"<em>\1</em>", text)

    chunks = [c.strip() for c in re.split(r"\n\s*\n", text) if c.strip()]

    out = []
    for chunk in chunks:
        lines = [l.strip() for l in chunk.split("\n") if l.strip()]

        if all(l.startswith(("- ", "* ")) for l in lines):
            items = "".join(f"<li>{l[2:].strip()}</li>" for l in lines)
            out.append(f"<ul>{items}</ul>")
            continue

        # A short chunk that is wholly bold reads as a section label.
        if len(lines) == 1 and lines[0].startswith("<strong>") \
                and lines[0].endswith("</strong>") and len(lines[0]) < 120:
            out.append(f"<h2>{lines[0][8:-9]}</h2>")
            continue

        out.append("<p>" + "<br>".join(lines) + "</p>")

    return "\n".join(out)


def _split_carry(body_html: str):
    """Pull the 'To carry today' section out so it can be styled separately."""
    marker = re.search(r"<h2>\s*To carry today\s*</h2>", body_html,
                       flags=re.IGNORECASE)
    if not marker:
        return body_html, None
    return body_html[:marker.start()].strip(), body_html[marker.end():].strip()


def _citation_lines(entry: dict) -> str:
    """Render the day's citations as stacked lines."""
    cites = entry.get("citations") or []
    if not cites:
        return ""
    return "<br>".join(html.escape(c) for c in cites)


def _page_shell(title: str, body: str, accent: str,
                description: str = "") -> str:
    desc = html.escape(description or SITE_TAGLINE)
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="cache-control" content="no-cache">
<title>{html.escape(title)}</title>
<meta name="description" content="{desc}">
<meta name="theme-color" content="#f7f4ef">
<meta property="og:title" content="{html.escape(title)}">
<meta property="og:description" content="{desc}">
<meta property="og:type" content="article">
<link rel="manifest" href="manifest.json">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400;0,500;1,400&display=swap">
<link rel="stylesheet" href="style.css">
<link rel="apple-touch-icon" href="icon.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="{html.escape(SITE_TITLE)}">
</head>
<body style="--accent: {accent};">
<div class="wrap">
  <div class="season-band"></div>
  <header class="site-head">
    <a class="brand" href="index.html">{html.escape(SITE_TITLE)}</a>
    <a class="archive-link" href="archive.html">Archive</a>
  </header>
{body}
  <footer class="site-foot">
    <p class="disclosure">{html.escape(DISCLOSURE)}</p>
  </footer>
</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Page builders
# ---------------------------------------------------------------------------
def _reflection_page(entry: dict, prev_date: str = None,
                     next_date: str = None) -> str:
    date_obj = datetime.date.fromisoformat(entry["date"])
    pretty = date_obj.strftime("%A &middot; %-d %B")
    full_date = date_obj.strftime("%A, %B %-d, %Y")

    accent = SEASON_COLORS.get(entry.get("color") or DEFAULT_COLOR,
                               SEASON_COLORS[DEFAULT_COLOR])

    body_html = _md_to_html(entry["reflection"])
    main_html, carry_html = _split_carry(body_html)

    heading = entry.get("liturgical_day") or full_date
    rank = entry.get("rank")
    epigraph = entry.get("epigraph")
    cites = _citation_lines(entry)

    rank_html = (f'<p class="rank">{html.escape(rank)}</p>' if rank else "")
    epi_html = (f'<div class="rule"></div>'
                f'<p class="epigraph">{html.escape(epigraph)}</p>'
                if epigraph else "")
    cite_html = f'<p class="citations">{cites}</p>' if cites else ""

    carry_block = ""
    if carry_html:
        carry_block = f"""
    <section class="carry">
      <p class="carry-label">To carry today</p>
      {carry_html}
    </section>"""

    if prev_date:
        prev_html = (f'<a href="{prev_date}.html">&larr; '
                     f'{datetime.date.fromisoformat(prev_date).strftime("%-d %b")}</a>')
    else:
        prev_html = "<span></span>"

    if next_date:
        next_html = (f'<a href="{next_date}.html">'
                     f'{datetime.date.fromisoformat(next_date).strftime("%-d %b")} &rarr;</a>')
    else:
        next_html = '<span class="nav-today">Today</span>'

    body = f"""
  <article class="entry">
    <div class="entry-head">
      <p class="date">{pretty}</p>
      <h1>{html.escape(heading)}</h1>
      {rank_html}
      {epi_html}
      {cite_html}
    </div>
    <div class="reflection">
{main_html}
    </div>{carry_block}
    <nav class="daynav">
      {prev_html}
      {next_html}
    </nav>
  </article>
"""
    return _page_shell(f"{heading} — {SITE_TITLE}", body, accent,
                       description=f"Readings and reflection for {full_date}")


def _archive_page(entries: list) -> str:
    by_month = {}
    for e in entries:
        d = datetime.date.fromisoformat(e["date"])
        by_month.setdefault(d.strftime("%B %Y"), []).append(e)

    sections = []
    for month, items in by_month.items():
        rows = []
        for e in items:
            d = datetime.date.fromisoformat(e["date"])
            label = e.get("liturgical_day") or d.strftime("%A")
            rows.append(
                f'<li><a href="{e["date"]}.html">'
                f'<span class="a-date">{d.strftime("%-d %a")}</span>'
                f'<span class="a-title">{html.escape(label)}</span></a></li>'
            )
        sections.append(
            f'<section class="month"><h2>{html.escape(month)}</h2>'
            f'<ul class="archive-list">{"".join(rows)}</ul></section>'
        )

    inner = "".join(sections) if sections else \
        '<p class="empty">No reflections yet.</p>'

    accent = SEASON_COLORS.get(
        (entries[0].get("color") if entries else DEFAULT_COLOR) or DEFAULT_COLOR,
        SEASON_COLORS[DEFAULT_COLOR])

    body = f"""
  <div class="entry">
    <div class="entry-head"><h1>Archive</h1></div>
    {inner}
  </div>
"""
    return _page_shell(f"Archive — {SITE_TITLE}", body, accent)


STYLE_CSS = """:root {
  --paper: #f7f4ef;
  --page: #efece5;
  --ink: #241f18;
  --ink-soft: #4a4238;
  --ink-faint: #9b9184;
  --rule: #ddd5c8;
  --panel: #efe9df;
  --accent: #5b7f4a;
}
@media (prefers-color-scheme: dark) {
  :root {
    --paper: #1a1814;
    --page: #121110;
    --ink: #ece6da;
    --ink-soft: #c3bbac;
    --ink-faint: #8b8275;
    --rule: #332e26;
    --panel: #221f19;
  }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--page);
  color: var(--ink);
  font-family: "EB Garamond", Georgia, serif;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}
.wrap { max-width: 34rem; margin: 0 auto; padding: 0 0 3rem; }
.season-band { height: 4px; background: var(--accent); }
.site-head {
  display: flex; justify-content: space-between; align-items: center;
  padding: 1.1rem 1.35rem 1.4rem;
}
.brand, .archive-link {
  font-size: .72rem; letter-spacing: .14em; text-transform: uppercase;
  color: var(--ink-faint); text-decoration: none;
}
.brand:hover, .archive-link:hover { color: var(--accent); }
.entry {
  background: var(--paper); border: .5px solid var(--rule);
  border-radius: 22px; padding: 1.9rem 1.5rem 1.6rem; margin: 0 .8rem;
}
.entry-head { text-align: center; }
.date {
  font-size: .72rem; letter-spacing: .17em; text-transform: uppercase;
  color: var(--ink-faint); margin: 0 0 .85rem;
}
h1 {
  font-size: 1.65rem; font-weight: 500; line-height: 1.25;
  color: var(--ink); margin: 0 0 .3rem;
}
.rank {
  font-style: italic; font-size: .95rem; color: var(--ink-faint);
  margin: 0 0 1.1rem;
}
.rule { width: 30px; height: .5px; background: var(--rule); margin: 1.1rem auto; }
.epigraph {
  font-style: italic; font-size: 1.08rem; line-height: 1.65;
  color: var(--ink-soft); margin: 0 0 1.25rem;
}
.citations {
  font-size: .85rem; line-height: 1.9; color: var(--ink-faint); margin: 0;
}
.reflection {
  border-top: .5px solid var(--rule); margin-top: 1.4rem; padding-top: 1.3rem;
  font-size: 1.04rem; line-height: 1.74; color: var(--ink);
}
.reflection h2 {
  font-size: .7rem; font-weight: 400; letter-spacing: .14em;
  text-transform: uppercase; color: var(--ink-faint);
  margin: 1.7rem 0 .55rem;
}
.reflection h2:first-child { margin-top: 0; }
.reflection p { margin: 0 0 1.05rem; }
.reflection ul { margin: 0 0 1.05rem; padding-left: 1.1rem; }
.reflection li { margin-bottom: .35rem; }
.reflection strong { font-weight: 500; }
.carry {
  background: var(--panel); border-radius: 16px;
  padding: 1.1rem 1.2rem; margin-top: 1.6rem; text-align: center;
}
.carry-label {
  font-size: .68rem; letter-spacing: .14em; text-transform: uppercase;
  color: var(--ink-faint); margin: 0 0 .5rem;
}
.carry p {
  font-style: italic; font-size: 1rem; line-height: 1.6;
  color: var(--ink-soft); margin: 0;
}
.daynav {
  display: flex; justify-content: space-between; align-items: center;
  margin-top: 1.5rem; padding-top: 1rem; border-top: .5px solid var(--rule);
  font-size: .88rem;
}
.daynav a { color: var(--accent); text-decoration: none; padding: .4rem 0; }
.nav-today { color: var(--ink-faint); }
.month h2 {
  font-size: .7rem; font-weight: 400; letter-spacing: .14em;
  text-transform: uppercase; color: var(--ink-faint); margin: 1.6rem 0 .5rem;
}
.archive-list { list-style: none; margin: 0; padding: 0; }
.archive-list li { border-bottom: .5px solid var(--rule); }
.archive-list a {
  display: flex; gap: .9rem; padding: .78rem 0;
  text-decoration: none; color: var(--ink);
}
.archive-list a:hover .a-title { color: var(--accent); }
.a-date {
  flex: 0 0 3.4rem; font-size: .82rem; color: var(--ink-faint);
  font-variant-numeric: tabular-nums;
}
.a-title { font-size: .98rem; }
.empty { color: var(--ink-faint); }
.site-foot { margin-top: 1.6rem; padding: 0 1.6rem; }
.disclosure {
  font-size: .72rem; line-height: 1.55; color: var(--ink-faint);
  margin: 0; text-align: center;
}
@media (min-width: 40rem) {
  .entry { padding: 2.4rem 2.6rem 2rem; }
  h1 { font-size: 1.9rem; }
}
"""

MANIFEST = {
    "name": SITE_TITLE,
    "short_name": "Readings",
    "description": SITE_TAGLINE,
    "start_url": "index.html",
    "display": "standalone",
    "background_color": "#f7f4ef",
    "theme_color": "#f7f4ef",
    "icons": [
        {"src": "icon.png", "sizes": "512x512", "type": "image/png",
         "purpose": "any maskable"}
    ],
}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def build_site(date: datetime.date, reflection: str, liturgical_day: str = None,
               rank: str = None, epigraph: str = None, citations: list = None,
               color: str = None) -> str:
    """
    Add today's reflection to the site and regenerate all pages.
    Returns the relative filename of today's page (e.g. "2026-07-22.html").
    """
    os.makedirs(DOCS_DIR, exist_ok=True)

    record_path = os.path.join(DOCS_DIR, "reflections.json")
    entries = []
    if os.path.exists(record_path):
        try:
            with open(record_path, encoding="utf-8") as f:
                entries = json.load(f)
        except (json.JSONDecodeError, OSError):
            entries = []

    iso = date.isoformat()
    entries = [e for e in entries if e.get("date") != iso]   # replace if re-run
    entries.append({
        "date": iso,
        "liturgical_day": liturgical_day,
        "rank": rank,
        "epigraph": epigraph,
        "citations": citations or [],
        "color": color or DEFAULT_COLOR,
        "reflection": reflection,
    })
    entries.sort(key=lambda e: e["date"], reverse=True)

    with open(record_path, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2, ensure_ascii=False)

    for i, entry in enumerate(entries):
        newer = entries[i - 1]["date"] if i > 0 else None
        older = entries[i + 1]["date"] if i + 1 < len(entries) else None
        page = _reflection_page(entry, prev_date=older, next_date=newer)
        with open(os.path.join(DOCS_DIR, f'{entry["date"]}.html'), "w",
                  encoding="utf-8") as f:
            f.write(page)

    newest = entries[0]
    home = _reflection_page(
        newest,
        prev_date=entries[1]["date"] if len(entries) > 1 else None,
        next_date=None,
    )
    with open(os.path.join(DOCS_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(home)

    with open(os.path.join(DOCS_DIR, "archive.html"), "w", encoding="utf-8") as f:
        f.write(_archive_page(entries))

    with open(os.path.join(DOCS_DIR, "style.css"), "w", encoding="utf-8") as f:
        f.write(STYLE_CSS)

    with open(os.path.join(DOCS_DIR, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(MANIFEST, f, indent=2)

    open(os.path.join(DOCS_DIR, ".nojekyll"), "w").close()

    return f"{iso}.html"
