#!/usr/bin/env python3
"""
site_builder.py — turns daily reflections into a small static website.

Called by daily_readings.py after a reflection is generated. Writes:

    docs/index.html            today's reflection (the homepage)
    docs/YYYY-MM-DD.html       a permanent page for each day
    docs/archive.html          list of every past day
    docs/style.css             shared styling
    docs/manifest.json         makes the site installable to a phone homescreen
    docs/reflections.json      machine-readable record of all entries

GitHub Pages serves the docs/ folder directly, so committing these files
publishes them. Nothing here talks to the network.
"""

import os
import re
import json
import html
import datetime

DOCS_DIR = "docs"
SITE_TITLE = "Daily Readings"
SITE_TAGLINE = "The day's Mass readings, with a reflection"

DISCLOSURE = (
    "Reflections are generated by AI from the day's readings and are offered "
    "as a starting point for prayer, not as authoritative commentary."
)

# Liturgical colors. Each season needs four values, because dark mode inverts
# the relationship: the header wants to be DARKER and the small accents
# LIGHTER against a near-black page.
#
#   head        header block background (light mode)
#   head_dark   header block background (dark mode)
#   accent      small accents: section labels, links (light mode)
#   accent_dark small accents (dark mode)
SEASON_COLORS = {
    "green":  {"head": "#4f7340", "head_dark": "#3c5731",
               "accent": "#5c7050", "accent_dark": "#9ab08c"},
    "purple": {"head": "#5f4a75", "head_dark": "#463659",
               "accent": "#6b5580", "accent_dark": "#b0a0c4"},
    "red":    {"head": "#8d332e", "head_dark": "#6a2622",
               "accent": "#94413b", "accent_dark": "#d19a95"},
    "white":  {"head": "#9c7d4f", "head_dark": "#75603c",
               "accent": "#8a6f45", "accent_dark": "#d4bc93"},
    "rose":   {"head": "#a86575", "head_dark": "#7d4a57",
               "accent": "#9c5e6d", "accent_dark": "#dcaeb9"},
}
DEFAULT_COLOR = "green"

# Labels shown beside each citation. Matched by position, with the psalm
# detected by name so the ordering stays right when a second reading appears.
CITATION_LABELS = ["First reading", "Psalm", "Second reading", "Gospel"]


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------
def _md_to_html(text: str) -> str:
    """Convert the light markdown Claude produces into simple HTML."""
    text = html.escape(text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*(?!\s)(.+?)(?<!\s)\*(?!\*)", r"<em>\1</em>", text)

    chunks = [c.strip() for c in re.split(r"\n\s*\n", text) if c.strip()]

    out = []
    for chunk in chunks:
        lines = [l.strip() for l in chunk.split("\n") if l.strip()]

        if all(l.startswith(("- ", "* ")) for l in lines):
            items = "".join(f"<li>{l[2:].strip()}</li>" for l in lines)
            out.append(f"<ul>{items}</ul>")
            continue

        if len(lines) == 1 and lines[0].startswith("<strong>") \
                and lines[0].endswith("</strong>") and len(lines[0]) < 130:
            out.append(f"<h2>{lines[0][8:-9]}</h2>")
            continue

        out.append("<p>" + "<br>".join(lines) + "</p>")

    return "\n".join(out)


def _split_carry(body_html: str):
    """Pull the 'To carry today' section out so it can be styled separately."""
    marker = re.search(r"<h2>\s*To carry today\s*</h2>", body_html,
                       flags=re.IGNORECASE)
    if not marker:
        return body_html, None
    return body_html[:marker.start()].strip(), body_html[marker.end():].strip()


def _label_citations(cites: list) -> list:
    """
    Pair each citation with a label. Works from the shape of the list:
    3 readings = first / psalm / gospel; 4 = first / psalm / second / gospel.
    Falls back to positional labels if the psalm isn't where expected.
    """
    if not cites:
        return []

    n = len(cites)
    if n == 3:
        labels = ["First reading", "Psalm", "Gospel"]
    elif n == 4:
        labels = ["First reading", "Psalm", "Second reading", "Gospel"]
    elif n == 2:
        labels = ["First reading", "Gospel"]
    else:
        labels = (CITATION_LABELS + [""] * n)[:n]

    # Sanity check: if something claiming to be the psalm isn't in the psalm
    # slot, don't mislabel — fall back to no labels at all.
    psalm_idx = next((i for i, c in enumerate(cites)
                      if c.lower().startswith("ps")), None)
    if psalm_idx is not None and labels[psalm_idx] != "Psalm":
        return [("", c) for c in cites]

    return list(zip(labels, cites))


def _citations_html(entry: dict) -> str:
    pairs = _label_citations(entry.get("citations") or [])
    if not pairs:
        return ""
    rows = "".join(
        f'<div class="cite-row">'
        f'<span class="cite-label">{html.escape(lbl)}</span>'
        f'<span class="cite-ref">{html.escape(ref)}</span></div>'
        for lbl, ref in pairs
    )
    return f'<div class="citations">{rows}</div>'


def _page_shell(title: str, body: str, colors: dict,
                description: str = "") -> str:
    desc = html.escape(description or SITE_TAGLINE)
    style_vars = (f"--head: {colors['head']}; "
                  f"--head-dark: {colors['head_dark']}; "
                  f"--accent-light: {colors['accent']}; "
                  f"--accent-dark: {colors['accent_dark']};")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="cache-control" content="no-cache">
<title>{html.escape(title)}</title>
<meta name="description" content="{desc}">
<meta name="theme-color" content="{colors['head']}">
<meta property="og:title" content="{html.escape(title)}">
<meta property="og:description" content="{desc}">
<meta property="og:type" content="article">
<link rel="manifest" href="manifest.json">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;1,8..60,400&display=swap">
<link rel="stylesheet" href="style.css">
<link rel="apple-touch-icon" href="icon.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="{html.escape(SITE_TITLE)}">
</head>
<body style="{style_vars}">
<div class="wrap">
  <header class="site-head">
    <a class="brand" href="index.html">{html.escape(SITE_TITLE)}</a>
    <a class="archive-link" href="archive.html">Archive</a>
  </header>
{body}
  <footer class="site-foot">
    <p class="disclosure">{html.escape(DISCLOSURE)}</p>
  </footer>
</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Page builders
# ---------------------------------------------------------------------------
def _reflection_page(entry: dict, prev_date: str = None,
                     next_date: str = None) -> str:
    date_obj = datetime.date.fromisoformat(entry["date"])
    pretty = date_obj.strftime("%A &middot; %-d %B")
    full_date = date_obj.strftime("%A, %B %-d, %Y")

    colors = SEASON_COLORS.get(entry.get("color") or DEFAULT_COLOR,
                               SEASON_COLORS[DEFAULT_COLOR])

    body_html = _md_to_html(entry["reflection"])
    main_html, carry_html = _split_carry(body_html)

    heading = entry.get("liturgical_day") or full_date
    rank = entry.get("rank")
    epigraph = entry.get("epigraph")

    rank_html = f'<p class="rank">{html.escape(rank)}</p>' if rank else ""
    epi_html = (f'<div class="rule"></div>'
                f'<p class="epigraph">{html.escape(epigraph)}</p>'
                if epigraph else "")
    cite_html = _citations_html(entry)

    carry_block = ""
    if carry_html:
        carry_block = f"""
    <section class="carry">
      <p class="carry-label">To carry today</p>
      {carry_html}
    </section>"""

    if prev_date:
        prev_html = (f'<a href="{prev_date}.html">&larr; '
                     f'{datetime.date.fromisoformat(prev_date).strftime("%-d %b")}</a>')
    else:
        prev_html = "<span></span>"

    if next_date:
        next_html = (f'<a href="{next_date}.html">'
                     f'{datetime.date.fromisoformat(next_date).strftime("%-d %b")} &rarr;</a>')
    else:
        next_html = '<span class="nav-today">Today</span>'

    body = f"""
  <article class="entry">
    <div class="entry-head">
      <p class="date">{pretty}</p>
      <h1>{html.escape(heading)}</h1>
      {rank_html}
      {epi_html}
      {cite_html}
    </div>
    <div class="entry-body">
      <div class="reflection">
{main_html}
      </div>{carry_block}
      <nav class="daynav">
        {prev_html}
        {next_html}
      </nav>
    </div>
  </article>
"""
    return _page_shell(f"{heading} — {SITE_TITLE}", body, colors,
                       description=f"Readings and reflection for {full_date}")


def _archive_page(entries: list) -> str:
    by_month = {}
    for e in entries:
        d = datetime.date.fromisoformat(e["date"])
        by_month.setdefault(d.strftime("%B %Y"), []).append(e)

    sections = []
    for month, items in by_month.items():
        rows = []
        for e in items:
            d = datetime.date.fromisoformat(e["date"])
            label = e.get("liturgical_day") or d.strftime("%A")
            dot = SEASON_COLORS.get(e.get("color") or DEFAULT_COLOR,
                                    SEASON_COLORS[DEFAULT_COLOR])["head"]
            rows.append(
                f'<li><a href="{e["date"]}.html">'
                f'<span class="a-dot" style="background:{dot}"></span>'
                f'<span class="a-date">{d.strftime("%-d %a")}</span>'
                f'<span class="a-title">{html.escape(label)}</span></a></li>'
            )
        sections.append(
            f'<section class="month"><h2>{html.escape(month)}</h2>'
            f'<ul class="archive-list">{"".join(rows)}</ul></section>'
        )

    inner = "".join(sections) if sections else \
        '<p class="empty">No reflections yet.</p>'

    colors = SEASON_COLORS.get(
        (entries[0].get("color") if entries else DEFAULT_COLOR) or DEFAULT_COLOR,
        SEASON_COLORS[DEFAULT_COLOR])

    body = f"""
  <article class="entry">
    <div class="entry-head">
      <h1>Archive</h1>
    </div>
    <div class="entry-body">
      {inner}
    </div>
  </article>
"""
    return _page_shell(f"Archive — {SITE_TITLE}", body, colors)


STYLE_CSS = """:root {
  --paper: #f8f5f0;
  --page: #efece5;
  --ink: #1f1b15;
  --ink-soft: #3d3529;
  --ink-faint: #7d7264;
  --rule: #ddd5c8;
  --panel: #eae4d8;
  --on-head: #ffffff;
  --on-head-soft: rgba(255,255,255,.72);
  --on-head-faint: rgba(255,255,255,.55);
  --head-rule: rgba(255,255,255,.3);
}
@media (prefers-color-scheme: dark) {
  :root {
    --paper: #1a1814;
    --page: #0e0d0c;
    --ink: #f0ebe1;
    --ink-soft: #cdc5b6;
    --ink-faint: #968c7e;
    --rule: #332e26;
    --panel: #221f19;
    --on-head: #f6f3ee;
    --on-head-soft: rgba(246,243,238,.74);
    --on-head-faint: rgba(246,243,238,.56);
    --head-rule: rgba(246,243,238,.26);
  }
}
body { --head-bg: var(--head); --accent: var(--accent-light); }
@media (prefers-color-scheme: dark) {
  body { --head-bg: var(--head-dark); --accent: var(--accent-dark); }
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: var(--page);
  color: var(--ink);
  font-family: "Source Serif 4", Georgia, serif;
  -webkit-font-smoothing: antialiased;
  text-rendering: optimizeLegibility;
}
.wrap { max-width: 36rem; margin: 0 auto; padding: 0 0 3rem; }
.site-head {
  display: flex; justify-content: space-between; align-items: center;
  padding: 1.1rem 1.35rem 1rem;
}
.brand, .archive-link {
  font-size: .76rem; font-weight: 600; letter-spacing: .13em;
  text-transform: uppercase; color: var(--ink-faint); text-decoration: none;
}
.brand:hover, .archive-link:hover { color: var(--accent); }
.entry {
  background: var(--paper); border: .5px solid var(--rule);
  border-radius: 22px; margin: 0 .8rem; overflow: hidden;
}
.entry-head {
  background: var(--head-bg); color: var(--on-head);
  text-align: center; padding: 2rem 1.55rem 1.75rem;
}
.date {
  font-size: .76rem; font-weight: 600; letter-spacing: .15em;
  text-transform: uppercase; color: var(--on-head-faint); margin: 0 0 .9rem;
}
.entry-head h1 {
  font-size: 1.7rem; font-weight: 600; line-height: 1.25;
  color: var(--on-head); margin: 0 0 .35rem;
}
.rank {
  font-style: italic; font-size: 1rem; color: var(--on-head-soft);
  margin: 0 0 1.1rem;
}
.rule { width: 32px; height: 1px; background: var(--head-rule); margin: 1.2rem auto; }
.epigraph {
  font-style: italic; font-size: 1.14rem; line-height: 1.65;
  color: var(--on-head-soft); margin: 0 0 1.4rem;
}
.citations {
  display: inline-block; text-align: left;
  border-top: .5px solid var(--head-rule); padding-top: 1rem;
}
.cite-row { display: flex; gap: .8rem; align-items: baseline; margin-bottom: .3rem; }
.cite-row:last-child { margin-bottom: 0; }
.cite-label {
  flex: 0 0 6.2rem; font-size: .72rem; font-weight: 600;
  letter-spacing: .1em; text-transform: uppercase;
  color: var(--on-head-faint);
}
.cite-ref { font-size: .96rem; color: var(--on-head-soft); }
.entry-body { padding: 1.7rem 1.55rem 1.6rem; }
.reflection { font-size: 1.14rem; line-height: 1.8; color: var(--ink); }
.reflection h2 {
  font-size: .78rem; font-weight: 600; letter-spacing: .12em;
  text-transform: uppercase; color: var(--accent);
  margin: 1.9rem 0 .6rem;
}
.reflection h2:first-child { margin-top: 0; }
.reflection p { margin: 0 0 1.2rem; }
.reflection ul { margin: 0 0 1.2rem; padding-left: 1.15rem; }
.reflection li { margin-bottom: .45rem; }
.reflection strong { font-weight: 600; }
.reflection em { font-style: italic; }
.carry {
  background: var(--panel); border-left: 3px solid var(--head-bg);
  padding: 1.2rem 1.3rem; margin-top: 1.8rem;
}
.carry-label {
  font-size: .74rem; font-weight: 600; letter-spacing: .13em;
  text-transform: uppercase; color: var(--accent); margin: 0 0 .55rem;
}
.carry p {
  font-style: italic; font-size: 1.08rem; line-height: 1.65;
  color: var(--ink-soft); margin: 0;
}
.daynav {
  display: flex; justify-content: space-between; align-items: center;
  margin-top: 1.7rem; padding-top: 1.1rem; border-top: .5px solid var(--rule);
  font-size: .95rem;
}
.daynav a { color: var(--accent); text-decoration: none; padding: .45rem 0; }
.nav-today { color: var(--ink-faint); }
.month h2 {
  font-size: .78rem; font-weight: 600; letter-spacing: .12em;
  text-transform: uppercase; color: var(--ink-faint); margin: 1.5rem 0 .55rem;
}
.month:first-child h2 { margin-top: 0; }
.archive-list { list-style: none; margin: 0; padding: 0; }
.archive-list li { border-bottom: .5px solid var(--rule); }
.archive-list a {
  display: flex; gap: .8rem; align-items: center; padding: .85rem 0;
  text-decoration: none; color: var(--ink);
}
.a-dot {
  flex: 0 0 7px; width: 7px; height: 7px; border-radius: 50%;
}
.a-date {
  flex: 0 0 3.5rem; font-size: .9rem; color: var(--ink-faint);
  font-variant-numeric: tabular-nums;
}
.a-title { font-size: 1.05rem; }
.archive-list a:hover .a-title { color: var(--accent); }
.empty { color: var(--ink-faint); }
.site-foot { margin-top: 1.7rem; padding: 0 1.6rem; }
.disclosure {
  font-size: .8rem; line-height: 1.55; color: var(--ink-faint);
  margin: 0; text-align: center;
}
@media (min-width: 40rem) {
  .entry-head { padding: 2.5rem 2.8rem 2.1rem; }
  .entry-body { padding: 2.1rem 2.8rem 1.9rem; }
  .entry-head h1 { font-size: 2rem; }
  .epigraph { font-size: 1.2rem; }
  .reflection { font-size: 1.18rem; }
}
"""

MANIFEST = {
    "name": SITE_TITLE,
    "short_name": "Readings",
    "description": SITE_TAGLINE,
    "start_url": "index.html",
    "display": "standalone",
    "background_color": "#f8f5f0",
    "theme_color": "#f8f5f0",
    "icons": [
        {"src": "icon.png", "sizes": "512x512", "type": "image/png",
         "purpose": "any maskable"}
    ],
}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def build_site(date: datetime.date, reflection: str, liturgical_day: str = None,
               rank: str = None, epigraph: str = None, citations: list = None,
               color: str = None) -> str:
    """
    Add today's reflection to the site and regenerate all pages.
    Returns the relative filename of today's page (e.g. "2026-07-22.html").
    """
    os.makedirs(DOCS_DIR, exist_ok=True)

    record_path = os.path.join(DOCS_DIR, "reflections.json")
    entries = []
    if os.path.exists(record_path):
        try:
            with open(record_path, encoding="utf-8") as f:
                entries = json.load(f)
        except (json.JSONDecodeError, OSError):
            entries = []

    iso = date.isoformat()
    entries = [e for e in entries if e.get("date") != iso]   # replace if re-run
    entries.append({
        "date": iso,
        "liturgical_day": liturgical_day,
        "rank": rank,
        "epigraph": epigraph,
        "citations": citations or [],
        "color": color or DEFAULT_COLOR,
        "reflection": reflection,
    })
    entries.sort(key=lambda e: e["date"], reverse=True)

    with open(record_path, "w", encoding="utf-8") as f:
        json.dump(entries, f, indent=2, ensure_ascii=False)

    for i, entry in enumerate(entries):
        newer = entries[i - 1]["date"] if i > 0 else None
        older = entries[i + 1]["date"] if i + 1 < len(entries) else None
        page = _reflection_page(entry, prev_date=older, next_date=newer)
        with open(os.path.join(DOCS_DIR, f'{entry["date"]}.html'), "w",
                  encoding="utf-8") as f:
            f.write(page)

    newest = entries[0]
    home = _reflection_page(
        newest,
        prev_date=entries[1]["date"] if len(entries) > 1 else None,
        next_date=None,
    )
    with open(os.path.join(DOCS_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(home)

    with open(os.path.join(DOCS_DIR, "archive.html"), "w", encoding="utf-8") as f:
        f.write(_archive_page(entries))

    with open(os.path.join(DOCS_DIR, "style.css"), "w", encoding="utf-8") as f:
        f.write(STYLE_CSS)

    with open(os.path.join(DOCS_DIR, "manifest.json"), "w", encoding="utf-8") as f:
        json.dump(MANIFEST, f, indent=2)

    open(os.path.join(DOCS_DIR, ".nojekyll"), "w").close()

    return f"{iso}.html"
